name: 每日下载 ip.zip 并提交

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间 9 点
  workflow_dispatch:      # 支持手动触发

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库代码
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 禁用默认 GitHub Token

      - name: 下载 ip.zip 文件
        run: |
          curl -L -O https://zip.cm.edu.kg/ip.zip
          file ip.zip
          ls -lh ip.zip

      - name: 配置 Git 用户信息
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 添加并提交 ip.zip
        run: |
          git add ip.zip
          git commit -m "自动下载 ip.zip：$(date +'%Y-%m-%d')" || echo "无变化，跳过提交"

      - name: 使用 PAT 推送提交
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git push
