name: 自动解压 ZIP 并提交

on:
  push:
    paths:
      - '*.zip'   # 当 ZIP 文件被上传或更新时触发

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 unzip 工具（一般已内置）
        run: sudo apt-get install unzip

      - name: 解压所有 ZIP 文件
        run: |
          for file in *.zip; do
            folder="${file%.*}"
            mkdir -p "$folder"
            unzip -o "$file" -d "$folder"
          done

      - name: 配置 Git 用户
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 提交解压文件
        run: |
          git add .
          git commit -m "解压 zip 并自动提交" || echo "无变更可提交"
          git push
