name: 自动解压 ZIP 并推送

on:
  push:
    paths:
      - '*.zip'   # 只有当 zip 文件被上传时才触发

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 解压所有 zip 文件
        run: |
          for file in *.zip; do
            dir="${file%.*}"
            mkdir -p "$dir"
            unzip -o "$file" -d "$dir"
          done

      - name: 配置 Git 身份
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 提交解压后的文件
        run: |
          git add .
          git commit -m "自动解压并提交 ZIP 文件内容" || echo "无变更可提交"
          git push
