name: 自动解压 ZIP 并提交

permissions:
  contents: write

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 解压 ZIP
        run: |
          for file in *.zip; do
            unzip -o "$file" -d "${file%.*}"
          done

      - name: 配置 Git 身份
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 提交解压内容
        run: |
          git add .
          git commit -m "自动解压 zip 并提交" || echo "无变更"
          git push
