name: 自动解压 ZIP 并处理文本

permissions:
  contents: write

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip-and-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 解压 ZIP 文件
        run: |
          for file in *.zip; do
            folder="${file%.*}"
            mkdir -p "$folder"
            unzip -o "$file" -d "$folder"
            rm "$file"
          done

      - name: 处理文本文件（跳过空行和已处理行）
        run: |
          # 遍历所有解压文件夹中的.txt文件
          find . -name "*.txt" | while read txtfile; do
            folder=$(dirname "$txtfile" | xargs basename)
            filename=$(basename "$txtfile" .txt)  # 去掉.txt后缀
            # 只为非空行，且未包含 :xxx#yyy 格式的行添加标记
            sed -i '/^[[:space:]]*$/! {/:[^:#]*#[^:#]*$/! s|$|:'"$folder"'#'"$filename"'|}' "$txtfile"
          done

      - name: 配置 Git 身份
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 提交更改
        run: |
          git add .
          git commit -m "解压并处理文本文件：为未标记的非空行添加文件夹和文件名标记(不含后缀)" || echo "无变更"
          git push
